"""Alert management endpoints."""
from fastapi import APIRouter, Depends, HTTPException, status, Query
from typing import List
from datetime import datetime
from backend.api.schemas.alerts import Alert, AlertResponse, CreateAlertRequest, UpdateAlertRequest, AlertListResponse, AlertStatus
from backend.api.schemas.auth import CurrentUser, UserRole
from backend.api.dependencies.auth import get_current_user
from backend.api.services.mock_data import MockDataService
from backend.api.schemas.errors import ErrorCode

router = APIRouter()


@router.get("/alerts", response_model=AlertListResponse)
async def get_alerts(
    zone_id: int | None = Query(None),
    status_filter: AlertStatus | None = Query(None),
    page: int = Query(1, ge=1),
    per_page: int = Query(10, ge=1, le=100),
    current_user: CurrentUser = Depends(get_current_user),
):
    """
    Get active alerts with optional filtering by zone and status.
    
    Required role: ADMIN, AUTHORITY, FIELD_OFFICER, CITIZEN
    
    Args:
        zone_id: Optional zone ID to filter by
        status_filter: Optional status to filter by
        page: Page number for pagination
        per_page: Items per page
        
    Returns:
        List of alerts with pagination metadata
    """
    try:
        # Get active alerts
        alerts = MockDataService.get_all_alerts()

        # Filter by zone if provided
        if zone_id:
            alerts = [a for a in alerts if a["zone_id"] == zone_id]

        # Filter by status if provided
        if status_filter:
            alerts = [a for a in alerts if a["status"] == status_filter]

        # Pagination
        total = len(alerts)
        start = (page - 1) * per_page
        end = start + per_page
        paginated_alerts = alerts[start:end]

        alert_responses = [AlertResponse(**alert) for alert in paginated_alerts]

        return AlertListResponse(
            alerts=alert_responses,
            total=total,
            page=page,
            per_page=per_page,
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": {
                    "code": ErrorCode.INTERNAL_ERROR,
                    "message": "Failed to fetch alerts",
                }
            },
        )


@router.post("/alerts", response_model=AlertResponse)
async def create_alert(
    request: CreateAlertRequest,
    current_user: CurrentUser = Depends(get_current_user),
):
    """
    Create a new alert for a zone.
    
    Required role: ADMIN, AUTHORITY, FIELD_OFFICER
    
    Args:
        request: Alert creation parameters
        
    Returns:
        Created alert
    """
    # Check authorization
    if current_user.role == UserRole.CITIZEN:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "error": {
                    "code": ErrorCode.INVALID_ROLE,
                    "message": "Citizens cannot create alerts",
                }
            },
        )

    # Verify zone exists
    zone = MockDataService.get_zone(request.zone_id)
    if not zone:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error": {
                    "code": ErrorCode.ZONE_NOT_FOUND,
                    "message": f"Zone {request.zone_id} not found",
                }
            },
        )

    try:
        # Create alert (mock - in real implementation would save to DB)
        alert = AlertResponse(
            alert_id=1001,  # Would be generated by DB
            zone_id=request.zone_id,
            zone_name=zone["zone_name"],
            risk_level=request.risk_level,
            status=AlertStatus.ACTIVE,
            triggered_at=datetime.now(),
            updated_at=datetime.now(),
            description=request.description,
            affected_population=request.affected_population,
            recommended_action=request.recommended_action,
        )
        return alert
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": {
                    "code": ErrorCode.INTERNAL_ERROR,
                    "message": "Failed to create alert",
                }
            },
        )


@router.patch("/alerts/{alert_id}", response_model=AlertResponse)
async def update_alert(
    alert_id: int,
    request: UpdateAlertRequest,
    current_user: CurrentUser = Depends(get_current_user),
):
    """
    Update alert status (acknowledge, mitigate, resolve).
    
    Required role: ADMIN, AUTHORITY, FIELD_OFFICER
    
    Args:
        alert_id: ID of alert to update
        request: Status update parameters
        
    Returns:
        Updated alert
    """
    # Check authorization
    if current_user.role == UserRole.CITIZEN:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "error": {
                    "code": ErrorCode.INVALID_ROLE,
                    "message": "Citizens cannot update alerts",
                }
            },
        )

    try:
        # Find alert (mock - in real implementation would query DB)
        alerts = MockDataService.get_all_alerts()
        alert = next((a for a in alerts if a["alert_id"] == alert_id), None)

        if not alert:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail={
                    "error": {
                        "code": ErrorCode.ALERT_NOT_FOUND,
                        "message": f"Alert {alert_id} not found",
                    }
                },
            )

        # Update status (mock)
        alert["status"] = request.status
        alert["updated_at"] = datetime.now()
        if request.status == AlertStatus.ACKNOWLEDGED:
            alert["acknowledged_by"] = current_user.user_id
            alert["acknowledged_at"] = datetime.now()
        elif request.status == AlertStatus.RESOLVED:
            alert["resolved_at"] = datetime.now()

        return AlertResponse(**alert)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": {
                    "code": ErrorCode.INTERNAL_ERROR,
                    "message": "Failed to update alert",
                }
            },
        )
