"""Report management endpoints."""
from fastapi import APIRouter, Depends, HTTPException, status, Query
from typing import List
from datetime import datetime
from backend.api.schemas.reports import Report, ReportResponse, CreateReportRequest, ReportListResponse, ReportStatus
from backend.api.schemas.auth import CurrentUser, UserRole
from backend.api.dependencies.auth import get_current_user
from backend.api.services.mock_data import MockDataService
from backend.api.schemas.errors import ErrorCode

router = APIRouter()


@router.post("/reports", response_model=ReportResponse)
async def create_report(
    request: CreateReportRequest,
    current_user: CurrentUser = Depends(get_current_user),
):
    """
    Create a new report (incident, assessment, prediction, or simulation).
    
    Required role: ADMIN, AUTHORITY, FIELD_OFFICER
    
    Args:
        request: Report creation parameters
        
    Returns:
        Created report
    """
    # Check authorization
    if current_user.role == UserRole.CITIZEN:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "error": {
                    "code": ErrorCode.INVALID_ROLE,
                    "message": "Citizens cannot create reports",
                }
            },
        )

    # Verify zone exists
    zone = MockDataService.get_zone(request.zone_id)
    if not zone:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error": {
                    "code": ErrorCode.ZONE_NOT_FOUND,
                    "message": f"Zone {request.zone_id} not found",
                }
            },
        )

    try:
        # Create report (mock - in real implementation would save to DB)
        report = ReportResponse(
            report_id=2001,  # Would be generated by DB
            report_type=request.report_type,
            zone_id=request.zone_id,
            zone_name=zone["zone_name"],
            title=request.title,
            description=request.description,
            created_by=current_user.user_id,
            created_at=datetime.now(),
            status=ReportStatus.SUBMITTED,
        )
        return report
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": {
                    "code": ErrorCode.INTERNAL_ERROR,
                    "message": "Failed to create report",
                }
            },
        )


@router.get("/reports", response_model=ReportListResponse)
async def get_reports(
    zone_id: int | None = Query(None),
    page: int = Query(1, ge=1),
    per_page: int = Query(10, ge=1, le=100),
    current_user: CurrentUser = Depends(get_current_user),
):
    """
    Get all reports with optional filtering.
    
    Required role: ADMIN, AUTHORITY
    
    Args:
        zone_id: Optional zone ID to filter by
        page: Page number for pagination
        per_page: Items per page
        
    Returns:
        List of reports with pagination
    """
    # Check authorization
    if current_user.role not in [UserRole.ADMIN, UserRole.AUTHORITY]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "error": {
                    "code": ErrorCode.INVALID_ROLE,
                    "message": "Only ADMIN and AUTHORITY can view all reports",
                }
            },
        )

    try:
        reports = MockDataService.get_all_reports()

        # Filter by zone if provided
        if zone_id:
            reports = [r for r in reports if r["zone_id"] == zone_id]

        # Pagination
        total = len(reports)
        start = (page - 1) * per_page
        end = start + per_page
        paginated_reports = reports[start:end]

        report_responses = [ReportResponse(**r) for r in paginated_reports]

        return ReportListResponse(
            reports=report_responses,
            total=total,
            page=page,
            per_page=per_page,
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": {
                    "code": ErrorCode.INTERNAL_ERROR,
                    "message": "Failed to fetch reports",
                }
            },
        )


@router.get("/reports/my", response_model=ReportListResponse)
async def get_my_reports(
    page: int = Query(1, ge=1),
    per_page: int = Query(10, ge=1, le=100),
    current_user: CurrentUser = Depends(get_current_user),
):
    """
    Get reports created by current user.
    
    Required role: ADMIN, AUTHORITY, FIELD_OFFICER
    
    Args:
        page: Page number for pagination
        per_page: Items per page
        
    Returns:
        User's reports with pagination
    """
    # Check authorization
    if current_user.role == UserRole.CITIZEN:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "error": {
                    "code": ErrorCode.INVALID_ROLE,
                    "message": "Citizens cannot view reports",
                }
            },
        )

    try:
        user_reports = MockDataService.get_all_reports()
        # Filter by current user (mock)
        user_reports = [r for r in user_reports if r["created_by"] == current_user.user_id or current_user.role == UserRole.ADMIN]

        # Pagination
        total = len(user_reports)
        start = (page - 1) * per_page
        end = start + per_page
        paginated_reports = user_reports[start:end]

        report_responses = [ReportResponse(**r) for r in paginated_reports]

        return ReportListResponse(
            reports=report_responses,
            total=total,
            page=page,
            per_page=per_page,
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": {
                    "code": ErrorCode.INTERNAL_ERROR,
                    "message": "Failed to fetch your reports",
                }
            },
        )
