import {
  DashboardSummary,
  RiskZone,
  Alert,
  Village,
  RoadSegment,
  HistoricalLandslide,
  CitizenReport,
} from './types';

export const mockDashboardSummary: DashboardSummary = {
  total_zones: 32,
  critical_zones: 4,
  high_zones: 9,
  moderate_zones: 12,
  low_zones: 7,
  active_alerts: 8,
  high_risk_villages: 18,
  blocked_roads_count: 3,
  last_updated: new Date().toISOString(),
};

export const mockRiskZones: RiskZone[] = [
  {
    zone_id: 'Z-NER-001',
    name: 'Sohra Slope Sector 4',
    state: 'Meghalaya',
    district: 'East Khasi Hills',
    risk_score: 88,
    risk_level: 'CRITICAL',
    confidence: 94,
    rainfall_mm: 312.4,
    soil_moisture: 91,
    slope_deg: 42.5,
    elevation_m: 1430,
    historical_events: 14,
    affected_villages: ['Sohra Village', 'Nongriat', 'Cherra Outskirts'],
    affected_roads: ['SH-11 Sohra Expressway', 'NH-206 Connecting Road'],
    risk_factors: [
      'Extreme 24h Accumulated Rainfall (>300mm)',
      'Saturated Sandstone Soil Layer',
      'Steep Escarpment (>40°)',
      'Historical Debris Slides',
    ],
    geometry: {
      lat: 25.282,
      lng: 91.727,
      coordinates: [
        [25.29, 91.72],
        [25.29, 91.74],
        [25.27, 91.74],
        [25.27, 91.72],
      ],
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-002',
    name: 'Gangtok Ridge South',
    state: 'Sikkim',
    district: 'East Sikkim',
    risk_score: 82,
    risk_level: 'CRITICAL',
    confidence: 91,
    rainfall_mm: 245.0,
    soil_moisture: 87,
    slope_deg: 38.0,
    elevation_m: 1650,
    historical_events: 11,
    affected_villages: ['Ranipool Upper', 'Tadong Hill Side'],
    affected_roads: ['NH-10 Highway', 'Gangtok Bypass'],
    risk_factors: [
      'Heavy Continuous Monsoon Precipitation',
      'High Slope Instability',
      'Road Cutting Activity at Base',
    ],
    geometry: {
      lat: 27.3389,
      lng: 88.6065,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-003',
    name: 'Kohima Bypass Escarpment',
    state: 'Nagaland',
    district: 'Kohima',
    risk_score: 79,
    risk_level: 'CRITICAL',
    confidence: 89,
    rainfall_mm: 198.5,
    soil_moisture: 84,
    slope_deg: 36.2,
    elevation_m: 1444,
    historical_events: 9,
    affected_villages: ['Kohima Village', 'Phesama Sector'],
    affected_roads: ['NH-2 Kohima-Imphal Highway'],
    risk_factors: [
      'Soil Shear Stress Exceeded',
      'Poor Drainage Channels',
      'Unconsolidated Shale Formations',
    ],
    geometry: {
      lat: 25.6747,
      lng: 94.11,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-004',
    name: 'Guwahati Kamakhya Hill Cut',
    state: 'Assam',
    district: 'Kamrup Metropolitan',
    risk_score: 76,
    risk_level: 'CRITICAL',
    confidence: 96,
    rainfall_mm: 165.2,
    soil_moisture: 82,
    slope_deg: 34.8,
    elevation_m: 290,
    historical_events: 18,
    affected_villages: ['Nilachal Settlement', 'Kamakhya Foothills'],
    affected_roads: ['Kamakhya Temple Hill Road', 'AT Road Junction'],
    risk_factors: [
      'Urban Hill Slope Cut Degradation',
      'Intense Short-Burst Downpour',
      'High Human Density at Slope Base',
    ],
    geometry: {
      lat: 26.1664,
      lng: 91.7066,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-005',
    name: 'Senapati NH-39 Corridor',
    state: 'Manipur',
    district: 'Senapati',
    risk_score: 68,
    risk_level: 'HIGH',
    confidence: 85,
    rainfall_mm: 154.0,
    soil_moisture: 78,
    slope_deg: 31.5,
    elevation_m: 950,
    historical_events: 7,
    affected_villages: ['Maram Village', 'Lairouching'],
    affected_roads: ['NH-39 Supply Lifeline'],
    risk_factors: ['High Soil Moisture', 'Active Creep Observed', 'Seismic Sensitivity Zone V'],
    geometry: {
      lat: 25.27,
      lng: 94.02,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-006',
    name: 'Lunglei Ridge North',
    state: 'Mizoram',
    district: 'Lunglei',
    risk_score: 64,
    risk_level: 'HIGH',
    confidence: 82,
    rainfall_mm: 142.8,
    soil_moisture: 75,
    slope_deg: 35.0,
    elevation_m: 1220,
    historical_events: 6,
    affected_villages: ['Zotlang', 'Chanmari Lunglei'],
    affected_roads: ['State Highway 2'],
    risk_factors: ['Moderate Creep', 'High Slope Angle', 'Clay Layer Saturation'],
    geometry: {
      lat: 22.88,
      lng: 92.73,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-007',
    name: 'Tawang Sela Pass Access',
    state: 'Arunachal Pradesh',
    district: 'Tawang',
    risk_score: 72,
    risk_level: 'HIGH',
    confidence: 88,
    rainfall_mm: 178.4,
    soil_moisture: 80,
    slope_deg: 44.0,
    elevation_m: 2850,
    historical_events: 12,
    affected_villages: ['Dirang Valley Edge', 'Sela Transit Outpost'],
    affected_roads: ['Bhalukpong-Tawang Highway'],
    risk_factors: ['Freeze-Thaw Rockfall Risk', 'Torrential Rain', 'Glacial Runoff Accumulation'],
    geometry: {
      lat: 27.53,
      lng: 91.86,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-008',
    name: 'Unakoti Heritage Hills',
    state: 'Tripura',
    district: 'Unakoti',
    risk_score: 42,
    risk_level: 'MODERATE',
    confidence: 80,
    rainfall_mm: 98.0,
    soil_moisture: 61,
    slope_deg: 24.5,
    elevation_m: 210,
    historical_events: 3,
    affected_villages: ['Kailashahar Rural', 'Unakoti Edge'],
    affected_roads: ['Kailashahar Main Road'],
    risk_factors: ['Moderate Soil Saturation', 'Soft Sandstone Weathering'],
    geometry: {
      lat: 24.32,
      lng: 92.08,
    },
    last_updated: new Date().toISOString(),
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'ALT-1001',
    zone_id: 'Z-NER-001',
    zone_name: 'Sohra Slope Sector 4',
    severity: 'CRITICAL',
    title: 'IMMINENT DEBRIS FLOW WARNING',
    description: '24h rainfall exceeded 300mm. Soil moisture at 91%. Evacuation of Nongriat and Sohra Outskirts is strongly advised.',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    acknowledged: false,
    evacuation_recommended: true,
  },
  {
    id: 'ALT-1002',
    zone_id: 'Z-NER-002',
    zone_name: 'Gangtok Ridge South',
    severity: 'CRITICAL',
    title: 'NH-10 HIGHWAY SUBSIDENCE RISK',
    description: 'Active ground movement detected near Ranipool. Road blockage highly probable within 6 hours.',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    acknowledged: false,
    evacuation_recommended: true,
  },
  {
    id: 'ALT-1003',
    zone_id: 'Z-NER-003',
    zone_name: 'Kohima Bypass Escarpment',
    severity: 'CRITICAL',
    title: 'SLOPE FAILURE WARNING - KOHIMA BYPASS',
    description: 'Soil shear stress threshold crossed. Traffic rerouting initiated on NH-2.',
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    acknowledged: true,
    evacuation_recommended: true,
  },
  {
    id: 'ALT-1004',
    zone_id: 'Z-NER-004',
    zone_name: 'Guwahati Kamakhya Hill Cut',
    severity: 'HIGH',
    title: 'URBAN SLOPE WASH OUT RISK',
    description: 'Localized intense downpour triggered high runoff across Nilachal settlement.',
    timestamp: new Date(Date.now() - 180 * 60000).toISOString(),
    acknowledged: true,
    evacuation_recommended: false,
  },
];

export const mockVillages: Village[] = [
  {
    id: 'V-101',
    name: 'Sohra Village',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    population: 4200,
    risk_score: 88,
    risk_level: 'CRITICAL',
    nearest_zone_id: 'Z-NER-001',
    coordinates: { lat: 25.281, lng: 91.725 },
  },
  {
    id: 'V-102',
    name: 'Nongriat',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    population: 850,
    risk_score: 92,
    risk_level: 'CRITICAL',
    nearest_zone_id: 'Z-NER-001',
    coordinates: { lat: 25.275, lng: 91.730 },
  },
  {
    id: 'V-103',
    name: 'Ranipool Upper',
    district: 'East Sikkim',
    state: 'Sikkim',
    population: 3100,
    risk_score: 82,
    risk_level: 'CRITICAL',
    nearest_zone_id: 'Z-NER-002',
    coordinates: { lat: 27.335, lng: 88.602 },
  },
  {
    id: 'V-104',
    name: 'Kohima Village Sector B',
    district: 'Kohima',
    state: 'Nagaland',
    population: 5600,
    risk_score: 79,
    risk_level: 'CRITICAL',
    nearest_zone_id: 'Z-NER-003',
    coordinates: { lat: 25.670, lng: 94.112 },
  },
];

export const mockRoadSegments: RoadSegment[] = [
  {
    id: 'R-201',
    name: 'SH-11 Sohra Highway Segment A',
    highway_code: 'SH-11',
    start_point: 'Shillong Bypass Junction',
    end_point: 'Sohra Bazaar',
    status: 'BLOCKED',
    risk_score: 91,
    coordinates: [
      [25.30, 91.72],
      [25.28, 91.727],
    ],
  },
  {
    id: 'R-202',
    name: 'NH-10 Siliguri-Gangtok Corridor',
    highway_code: 'NH-10',
    start_point: 'Ranipool Gate',
    end_point: 'Gangtok Zero Point',
    status: 'HIGH_RISK',
    risk_score: 84,
    coordinates: [
      [27.32, 88.60],
      [27.34, 88.61],
    ],
  },
  {
    id: 'R-203',
    name: 'NH-2 Kohima-Imphal Lifeline',
    highway_code: 'NH-2',
    start_point: 'Kohima North Checkpoint',
    end_point: 'Phesama Ridge',
    status: 'WARNING',
    risk_score: 77,
    coordinates: [
      [25.66, 94.10],
      [25.68, 94.12],
    ],
  },
];

export const mockHistoricalLandslides: HistoricalLandslide[] = [
  {
    id: 'H-901',
    date: '2024-06-18',
    location: 'Sohra Escarpment Sector 3',
    state: 'Meghalaya',
    district: 'East Khasi Hills',
    risk_score_at_event: 92,
    rainfall_recorded_mm: 410.5,
    slope_deg: 43.0,
    casualties: 4,
    damage_summary: 'Major road wash-out on SH-11, 3 houses damaged in upper valley.',
  },
  {
    id: 'H-902',
    date: '2023-07-12',
    location: 'Ranipool Slope',
    state: 'Sikkim',
    district: 'East Sikkim',
    risk_score_at_event: 86,
    rainfall_recorded_mm: 290.0,
    slope_deg: 39.5,
    casualties: 2,
    damage_summary: 'Highway NH-10 blocked for 72 hours due to mudslide and heavy boulders.',
  },
  {
    id: 'H-903',
    date: '2022-09-04',
    location: 'Guwahati Maligaon Hill',
    state: 'Assam',
    district: 'Kamrup Metropolitan',
    risk_score_at_event: 81,
    rainfall_recorded_mm: 195.0,
    slope_deg: 36.0,
    casualties: 0,
    damage_summary: 'Retaining wall collapse damaging 2 vehicle tracks.',
  },
  {
    id: 'H-904',
    date: '2022-05-24',
    location: 'Dima Hasao Railway Slope',
    state: 'Assam',
    district: 'Dima Hasao',
    risk_score_at_event: 95,
    rainfall_recorded_mm: 365.0,
    slope_deg: 41.0,
    casualties: 5,
    damage_summary: 'Severe railway line destruction and multiple land slips across Lumding-Badarpur route.',
  },
];

export const mockReports: CitizenReport[] = [
  {
    id: 'REP-501',
    zone_id: 'Z-NER-001',
    reporter_type: 'FIELD_AGENT',
    location_description: 'Near kilometer mark 14 on Sohra Road',
    report_type: 'SOIL_CRACK',
    urgency: 'HIGH',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    verified: true,
  },
  {
    id: 'REP-502',
    zone_id: 'Z-NER-004',
    reporter_type: 'CITIZEN',
    location_description: 'West Kamakhya slope near staircase',
    report_type: 'ROCKFALL',
    urgency: 'MEDIUM',
    timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
    verified: true,
  },
];
