import {
  DashboardSummary,
  RiskZone,
  Alert,
  Village,
  RoadSegment,
  HistoricalLandslide,
  CitizenReport,
  DataSourceStatus,
  IngestionRun,
} from './types';

export const mockDashboardSummary: DashboardSummary = {
  total_zones: 32,
  critical_zones: 4,
  high_zones: 9,
  moderate_zones: 12,
  low_zones: 7,
  active_alerts: 8,
  high_risk_villages: 18,
  blocked_roads_count: 3,
  last_updated: new Date().toISOString(),
};

export const mockRiskZones: RiskZone[] = [
  {
    zone_id: 'Z-NER-001',
    name: 'Sohra Slope Sector 4',
    state: 'Meghalaya',
    district: 'East Khasi Hills',
    risk_score: 88,
    risk_level: 'CRITICAL',
    confidence: 94,
    rainfall_mm: 312.4,
    soil_moisture: 91,
    slope_deg: 42.5,
    elevation_m: 1430,
    historical_events: 14,
    affected_villages: ['Sohra Village', 'Nongriat', 'Cherra Outskirts'],
    affected_roads: ['SH-11 Sohra Expressway', 'NH-206 Connecting Road'],
    risk_factors: [
      'Extreme 24h Accumulated Rainfall (>300mm)',
      'Saturated Sandstone Soil Layer',
      'Steep Escarpment (>40°)',
      'Historical Debris Slides',
    ],
    geometry: {
      lat: 25.282,
      lng: 91.727,
      coordinates: [
        [25.29, 91.72],
        [25.29, 91.74],
        [25.27, 91.74],
        [25.27, 91.72],
      ],
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-002',
    name: 'Gangtok Ridge South',
    state: 'Sikkim',
    district: 'East Sikkim',
    risk_score: 82,
    risk_level: 'CRITICAL',
    confidence: 91,
    rainfall_mm: 245.0,
    soil_moisture: 87,
    slope_deg: 38.0,
    elevation_m: 1650,
    historical_events: 11,
    affected_villages: ['Ranipool Upper', 'Tadong Hill Side'],
    affected_roads: ['NH-10 Highway', 'Gangtok Bypass'],
    risk_factors: [
      'Heavy Continuous Monsoon Precipitation',
      'High Slope Instability',
      'Road Cutting Activity at Base',
    ],
    geometry: {
      lat: 27.3389,
      lng: 88.6065,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-003',
    name: 'Kohima Bypass Escarpment',
    state: 'Nagaland',
    district: 'Kohima',
    risk_score: 79,
    risk_level: 'CRITICAL',
    confidence: 89,
    rainfall_mm: 198.5,
    soil_moisture: 84,
    slope_deg: 36.2,
    elevation_m: 1444,
    historical_events: 9,
    affected_villages: ['Kohima Village', 'Phesama Sector'],
    affected_roads: ['NH-2 Kohima-Imphal Highway'],
    risk_factors: [
      'Soil Shear Stress Exceeded',
      'Poor Drainage Channels',
      'Unconsolidated Shale Formations',
    ],
    geometry: {
      lat: 25.6747,
      lng: 94.11,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-004',
    name: 'Guwahati Kamakhya Hill Cut',
    state: 'Assam',
    district: 'Kamrup Metropolitan',
    risk_score: 76,
    risk_level: 'CRITICAL',
    confidence: 96,
    rainfall_mm: 165.2,
    soil_moisture: 82,
    slope_deg: 34.8,
    elevation_m: 290,
    historical_events: 18,
    affected_villages: ['Nilachal Settlement', 'Kamakhya Foothills'],
    affected_roads: ['Kamakhya Temple Hill Road', 'AT Road Junction'],
    risk_factors: [
      'Urban Hill Slope Cut Degradation',
      'Intense Short-Burst Downpour',
      'High Human Density at Slope Base',
    ],
    geometry: {
      lat: 26.1664,
      lng: 91.7066,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-005',
    name: 'Senapati NH-39 Corridor',
    state: 'Manipur',
    district: 'Senapati',
    risk_score: 68,
    risk_level: 'HIGH',
    confidence: 85,
    rainfall_mm: 154.0,
    soil_moisture: 78,
    slope_deg: 31.5,
    elevation_m: 950,
    historical_events: 7,
    affected_villages: ['Maram Village', 'Lairouching'],
    affected_roads: ['NH-39 Supply Lifeline'],
    risk_factors: ['High Soil Moisture', 'Active Creep Observed', 'Seismic Sensitivity Zone V'],
    geometry: {
      lat: 25.27,
      lng: 94.02,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-006',
    name: 'Lunglei Ridge North',
    state: 'Mizoram',
    district: 'Lunglei',
    risk_score: 64,
    risk_level: 'HIGH',
    confidence: 82,
    rainfall_mm: 142.8,
    soil_moisture: 75,
    slope_deg: 35.0,
    elevation_m: 1220,
    historical_events: 6,
    affected_villages: ['Zotlang', 'Chanmari Lunglei'],
    affected_roads: ['State Highway 2'],
    risk_factors: ['Moderate Creep', 'High Slope Angle', 'Clay Layer Saturation'],
    geometry: {
      lat: 22.88,
      lng: 92.73,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-007',
    name: 'Tawang Sela Pass Access',
    state: 'Arunachal Pradesh',
    district: 'Tawang',
    risk_score: 72,
    risk_level: 'HIGH',
    confidence: 88,
    rainfall_mm: 178.4,
    soil_moisture: 80,
    slope_deg: 44.0,
    elevation_m: 2850,
    historical_events: 12,
    affected_villages: ['Dirang Valley Edge', 'Sela Transit Outpost'],
    affected_roads: ['Bhalukpong-Tawang Highway'],
    risk_factors: ['Freeze-Thaw Rockfall Risk', 'Torrential Rain', 'Glacial Runoff Accumulation'],
    geometry: {
      lat: 27.53,
      lng: 91.86,
    },
    last_updated: new Date().toISOString(),
  },
  {
    zone_id: 'Z-NER-008',
    name: 'Unakoti Heritage Hills',
    state: 'Tripura',
    district: 'Unakoti',
    risk_score: 42,
    risk_level: 'MODERATE',
    confidence: 80,
    rainfall_mm: 98.0,
    soil_moisture: 61,
    slope_deg: 24.5,
    elevation_m: 210,
    historical_events: 3,
    affected_villages: ['Kailashahar Rural', 'Unakoti Edge'],
    affected_roads: ['Kailashahar Main Road'],
    risk_factors: ['Moderate Soil Saturation', 'Soft Sandstone Weathering'],
    geometry: {
      lat: 24.32,
      lng: 92.08,
    },
    last_updated: new Date().toISOString(),
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'ALT-1001',
    zone_id: 'Z-NER-001',
    zone_name: 'Sohra Slope Sector 4',
    severity: 'CRITICAL',
    title: 'IMMINENT DEBRIS FLOW WARNING',
    description: '24h rainfall exceeded 300mm. Soil moisture at 91%. Evacuation of Nongriat and Sohra Outskirts is strongly advised.',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    acknowledged: false,
    evacuation_recommended: true,
  },
  {
    id: 'ALT-1002',
    zone_id: 'Z-NER-002',
    zone_name: 'Gangtok Ridge South',
    severity: 'CRITICAL',
    title: 'NH-10 HIGHWAY SUBSIDENCE RISK',
    description: 'Active ground movement detected near Ranipool. Road blockage highly probable within 6 hours.',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    acknowledged: false,
    evacuation_recommended: true,
  },
  {
    id: 'ALT-1003',
    zone_id: 'Z-NER-003',
    zone_name: 'Kohima Bypass Escarpment',
    severity: 'CRITICAL',
    title: 'SLOPE FAILURE WARNING - KOHIMA BYPASS',
    description: 'Soil shear stress threshold crossed. Traffic rerouting initiated on NH-2.',
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    acknowledged: true,
    evacuation_recommended: true,
  },
  {
    id: 'ALT-1004',
    zone_id: 'Z-NER-004',
    zone_name: 'Guwahati Kamakhya Hill Cut',
    severity: 'HIGH',
    title: 'URBAN SLOPE WASH OUT RISK',
    description: 'Localized intense downpour triggered high runoff across Nilachal settlement.',
    timestamp: new Date(Date.now() - 180 * 60000).toISOString(),
    acknowledged: true,
    evacuation_recommended: false,
  },
];

export const mockVillages: Village[] = [
  {
    id: 'V-101',
    name: 'Sohra Village',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    population: 4200,
    risk_score: 88,
    risk_level: 'CRITICAL',
    nearest_zone_id: 'Z-NER-001',
    coordinates: { lat: 25.281, lng: 91.725 },
  },
  {
    id: 'V-102',
    name: 'Nongriat',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    population: 850,
    risk_score: 92,
    risk_level: 'CRITICAL',
    nearest_zone_id: 'Z-NER-001',
    coordinates: { lat: 25.275, lng: 91.730 },
  },
  {
    id: 'V-103',
    name: 'Ranipool Upper',
    district: 'East Sikkim',
    state: 'Sikkim',
    population: 3100,
    risk_score: 82,
    risk_level: 'CRITICAL',
    nearest_zone_id: 'Z-NER-002',
    coordinates: { lat: 27.335, lng: 88.602 },
  },
  {
    id: 'V-104',
    name: 'Kohima Village Sector B',
    district: 'Kohima',
    state: 'Nagaland',
    population: 5600,
    risk_score: 79,
    risk_level: 'CRITICAL',
    nearest_zone_id: 'Z-NER-003',
    coordinates: { lat: 25.670, lng: 94.112 },
  },
];

export const mockRoadSegments: RoadSegment[] = [
  {
    id: 'R-201',
    name: 'SH-11 Sohra Highway Segment A',
    highway_code: 'SH-11',
    start_point: 'Shillong Bypass Junction',
    end_point: 'Sohra Bazaar',
    status: 'BLOCKED',
    risk_score: 91,
    coordinates: [
      [25.30, 91.72],
      [25.28, 91.727],
    ],
  },
  {
    id: 'R-202',
    name: 'NH-10 Siliguri-Gangtok Corridor',
    highway_code: 'NH-10',
    start_point: 'Ranipool Gate',
    end_point: 'Gangtok Zero Point',
    status: 'HIGH_RISK',
    risk_score: 84,
    coordinates: [
      [27.32, 88.60],
      [27.34, 88.61],
    ],
  },
  {
    id: 'R-203',
    name: 'NH-2 Kohima-Imphal Lifeline',
    highway_code: 'NH-2',
    start_point: 'Kohima North Checkpoint',
    end_point: 'Phesama Ridge',
    status: 'WARNING',
    risk_score: 77,
    coordinates: [
      [25.66, 94.10],
      [25.68, 94.12],
    ],
  },
];

export const mockHistoricalLandslides: HistoricalLandslide[] = [
  {
    id: 'H-901',
    date: '2024-06-18',
    location: 'Sohra Escarpment Sector 3',
    state: 'Meghalaya',
    district: 'East Khasi Hills',
    latitude: 25.282,
    longitude: 91.727,
    risk_score_at_event: 92,
    rainfall_recorded_mm: 410.5,
    slope_deg: 43.0,
    casualties: 4,
    damage_summary: 'Major road wash-out on SH-11, 3 houses damaged in upper valley.',
    source_name: 'Meghalaya State Disaster Management Authority (SDMA)',
    certainty: 'confirmed_instrumented',
    provenance: 'static_reference',
  },
  {
    id: 'H-902',
    date: '2023-07-12',
    location: 'Ranipool Slope, Gangtok Ridge',
    state: 'Sikkim',
    district: 'East Sikkim',
    latitude: 27.305,
    longitude: 88.591,
    risk_score_at_event: 86,
    rainfall_recorded_mm: 290.0,
    slope_deg: 39.5,
    casualties: 2,
    damage_summary: 'Highway NH-10 blocked for 72 hours due to mudslide and heavy boulders.',
    source_name: 'Border Roads Organisation (BRO) Project Swastik',
    certainty: 'confirmed_instrumented',
    provenance: 'static_reference',
  },
  {
    id: 'H-903',
    date: '2022-09-04',
    location: 'Guwahati Maligaon Hill',
    state: 'Assam',
    district: 'Kamrup Metropolitan',
    latitude: 26.155,
    longitude: 91.688,
    risk_score_at_event: 81,
    rainfall_recorded_mm: 195.0,
    slope_deg: 36.0,
    casualties: 0,
    damage_summary: 'Retaining wall collapse damaging 2 vehicle tracks.',
    source_name: 'Assam State Disaster Management Authority',
    certainty: 'confirmed_field_report',
    provenance: 'static_reference',
  },
  {
    id: 'H-904',
    date: '2022-05-24',
    location: 'Dima Hasao Railway Slope',
    state: 'Assam',
    district: 'Dima Hasao',
    latitude: 25.178,
    longitude: 93.024,
    risk_score_at_event: 95,
    rainfall_recorded_mm: 365.0,
    slope_deg: 41.0,
    casualties: 5,
    damage_summary: 'Severe railway line destruction and multiple land slips across Lumding-Badarpur route.',
    source_name: 'Northeast Frontier Railway (NFR) Disaster Cell',
    certainty: 'confirmed_instrumented',
    provenance: 'static_reference',
  },
  {
    id: 'H-905',
    date: '2021-10-19',
    location: 'Almora - Ranikhet Highway & Nainital Slopes',
    state: 'Uttarakhand',
    district: 'Almora',
    latitude: 29.632,
    longitude: 79.415,
    risk_score_at_event: 89,
    rainfall_recorded_mm: 340.0,
    slope_deg: 38.0,
    casualties: 28,
    damage_summary: 'Extreme 48h unseasonal rain caused massive slope washouts across Almora, Ranikhet link roads and Nainital highway NH-109.',
    source_name: 'Uttarakhand State Disaster Management Authority (USDMA)',
    certainty: 'confirmed_instrumented',
    provenance: 'static_reference',
  },
  {
    id: 'H-906',
    date: '2023-01-05',
    location: 'Joshimath Subsidence & Marwari Slope',
    state: 'Uttarakhand',
    district: 'Chamoli',
    latitude: 30.556,
    longitude: 79.566,
    risk_score_at_event: 94,
    rainfall_recorded_mm: 45.0,
    slope_deg: 32.0,
    casualties: 0,
    damage_summary: 'Deep ground fissures, structural displacement of 860+ buildings, emergency evacuation of Sunil and Manohar Bagh wards.',
    source_name: 'Geological Survey of India (GSI) Expert Committee',
    certainty: 'confirmed_instrumented',
    provenance: 'static_reference',
  },
  {
    id: 'H-907',
    date: '2024-05-28',
    location: 'Melthum & Hlimen Quarry Slopes, Aizawl',
    state: 'Mizoram',
    district: 'Aizawl',
    latitude: 23.702,
    longitude: 92.723,
    risk_score_at_event: 96,
    rainfall_recorded_mm: 285.0,
    slope_deg: 44.0,
    casualties: 34,
    damage_summary: 'Multiple landslides triggered by Cyclone Remal remnants, washing down stone quarries and dwelling houses into gorge.',
    source_name: 'Mizoram Disaster Management & Rehabilitation Dept',
    certainty: 'confirmed_instrumented',
    provenance: 'static_reference',
  },
  {
    id: 'H-908',
    date: '2024-06-13',
    location: 'Mangan - Chungthang Highway Slope',
    state: 'Sikkim',
    district: 'Mangan',
    latitude: 27.502,
    longitude: 88.538,
    risk_score_at_event: 93,
    rainfall_recorded_mm: 310.0,
    slope_deg: 45.0,
    casualties: 6,
    damage_summary: 'Severe road severance at Sankalang bridge, isolating North Sikkim and triggering emergency airlift operations.',
    source_name: 'Sikkim SDMA & Indian Army Trishakti Corps',
    certainty: 'confirmed_instrumented',
    provenance: 'static_reference',
  },
];

export const mockReports: CitizenReport[] = [
  {
    id: 'REP-501',
    zone_id: 'Z-NER-001',
    reporter_type: 'FIELD_AGENT',
    location_description: 'Near kilometer mark 14 on Sohra Road',
    report_type: 'SOIL_CRACK',
    urgency: 'HIGH',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    verified: true,
  },
  {
    id: 'REP-502',
    zone_id: 'Z-NER-004',
    reporter_type: 'CITIZEN',
    location_description: 'West Kamakhya slope near staircase',
    report_type: 'ROCKFALL',
    urgency: 'MEDIUM',
    timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
    verified: true,
  },
];

export const mockDataSources: DataSourceStatus[] = [
  {
    slug: 'open-meteo',
    name: 'Open-Meteo High-Resolution Forecast',
    category: 'weather_soil',
    provider: 'Open-Meteo GmbH',
    access_type: 'public_api',
    provenance: 'live_modelled',
    status: 'configured',
    license_name: 'Open Data Commons (ODbL)',
    attribution: 'Weather forecasts by Open-Meteo',
    credential_env: 'No secret required (Public endpoint)',
    last_success_at: new Date(Date.now() - 15 * 60000).toISOString(),
    freshness_seconds: 900,
    metadata: { version: 'v1.1', resolution_km: 1.0, update_frequency: 'hourly' },
    credential_configured: true,
    file_import_available: false,
    provider_adapter_status: 'available',
    accepted_formats: [],
    authorization_required: false,
    operator_guidance: 'Live hourly precipitation and multi-layer soil moisture (0-7cm & 7-28cm) for all 8 NER states.',
  },
  {
    slug: 'cdse-stac',
    name: 'Copernicus Data Space STAC Catalogue',
    category: 'satellite',
    provider: 'European Space Agency (ESA)',
    access_type: 'public_catalogue',
    provenance: 'static_reference',
    status: 'configured',
    attribution: 'Contains modified Copernicus Sentinel data',
    credential_env: 'No secret required',
    last_success_at: new Date(Date.now() - 45 * 60000).toISOString(),
    freshness_seconds: 3600,
    metadata: { standard: 'STAC 1.0', collections: ['sentinel-1-grd', 'sentinel-2-l2a'] },
    credential_configured: true,
    file_import_available: false,
    provider_adapter_status: 'available',
    accepted_formats: [],
    authorization_required: false,
    operator_guidance: 'Searches Sentinel-1 SAR and Sentinel-2 optical scenes over monitored mountain corridors.',
  },
  {
    slug: 'cdse-process',
    name: 'Copernicus Sentinel Hub Process API',
    category: 'satellite',
    provider: 'European Space Agency (ESA)',
    access_type: 'oauth_client',
    provenance: 'cached_observed',
    status: 'credentials_optional',
    attribution: 'Contains modified Copernicus Sentinel data',
    credential_env: 'CDSE_CLIENT_ID / CDSE_CLIENT_SECRET',
    last_success_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    freshness_seconds: 86400,
    metadata: { product: 'Sentinel-1 GRD SAR & Sentinel-2 L2A BOA' },
    credential_configured: true,
    file_import_available: false,
    provider_adapter_status: 'available',
    accepted_formats: ['.tif', '.tiff'],
    authorization_required: false,
    operator_guidance: 'Downloads analysis-ready cloud-penetrating SAR radar backscatter and optical NDVI/moisture rasters.',
  },
  {
    slug: 'imd',
    name: 'India Meteorological Department (IMD)',
    category: 'weather',
    provider: 'Ministry of Earth Sciences, Govt of India',
    access_type: 'institutional',
    provenance: 'cached_observed',
    status: 'provider_contract_required',
    credential_env: 'IMD_API_KEY',
    last_success_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    freshness_seconds: 7200,
    metadata: { network: 'NER Doppler Weather Radar & AWS Stations' },
    credential_configured: true,
    file_import_available: true,
    provider_adapter_status: 'authorized_file_import_ready',
    accepted_formats: ['.csv', '.json', '.geojson', '.nc', '.h5', '.hdf'],
    authorization_required: true,
    operator_guidance: 'Official station observations, 24h rain gauges, and Cherrapunji Doppler radar scans. Authorized file import supported.',
  },
  {
    slug: 'gsi',
    name: 'GSI Bhusanket / NLSM Landslide Portal',
    category: 'geology_landslides',
    provider: 'Geological Survey of India',
    access_type: 'institutional',
    provenance: 'cached_observed',
    status: 'provider_contract_required',
    credential_env: 'GSI_API_KEY',
    last_success_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    freshness_seconds: 86400,
    metadata: { program: 'National Landslide Susceptibility Mapping (NLSM)' },
    credential_configured: true,
    file_import_available: true,
    provider_adapter_status: 'authorized_file_import_ready',
    accepted_formats: ['.csv', '.json', '.geojson', '.tif', '.tiff', '.zip'],
    authorization_required: true,
    operator_guidance: 'Official Indian landslide hazard macro-zonation and historical landslide inventory. Retains verified event uncertainty.',
  },
  {
    slug: 'bhuvan',
    name: 'NRSC Bhuvan / Bhoonidhi Portal',
    category: 'satellite_terrain',
    provider: 'ISRO / National Remote Sensing Centre',
    access_type: 'institutional',
    provenance: 'cached_observed',
    status: 'provider_contract_required',
    credential_env: 'BHUVAN_API_KEY',
    last_success_at: new Date(Date.now() - 3600000 * 6).toISOString(),
    freshness_seconds: 86400,
    metadata: { sensor: 'Cartosat-3 DEM & Resourcesat LISS-IV' },
    credential_configured: true,
    file_import_available: true,
    provider_adapter_status: 'authorized_file_import_ready',
    accepted_formats: ['.tif', '.tiff', '.json', '.geojson', '.zip', '.h5', '.hdf'],
    authorization_required: true,
    operator_guidance: 'High-resolution indigenous digital elevation models (DEM) and multi-spectral terrain imagery for slope stability modeling.',
  },
  {
    slug: 'mosdac',
    name: 'MOSDAC Meteorological Satellite Feed',
    category: 'satellite_weather',
    provider: 'Space Applications Centre (SAC / ISRO)',
    access_type: 'institutional',
    provenance: 'cached_observed',
    status: 'provider_contract_required',
    credential_env: 'MOSDAC_API_KEY',
    last_success_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    freshness_seconds: 10800,
    metadata: { satellites: ['INSAT-3D', 'INSAT-3DR'] },
    credential_configured: true,
    file_import_available: true,
    provider_adapter_status: 'authorized_file_import_ready',
    accepted_formats: ['.tif', '.tiff', '.nc', '.h5', '.hdf', '.json', '.zip'],
    authorization_required: true,
    operator_guidance: 'INSAT-3DR rapid-scan infrared and water-vapor satellite imagery for convective storm tracking over the Himalayas.',
  },
  {
    slug: 'india-wris',
    name: 'CWC / India-WRIS Water Resources Info',
    category: 'hydrology',
    provider: 'Central Water Commission (CWC)',
    access_type: 'institutional',
    provenance: 'cached_observed',
    status: 'provider_contract_required',
    credential_env: 'INDIA_WRIS_API_KEY',
    last_success_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    freshness_seconds: 14400,
    metadata: { rivers: ['Brahmaputra', 'Barak', 'Teesta'] },
    credential_configured: true,
    file_import_available: true,
    provider_adapter_status: 'authorized_file_import_ready',
    accepted_formats: ['.csv', '.json', '.geojson', '.nc', '.zip'],
    authorization_required: true,
    operator_guidance: 'River water-level stations, flood discharge warnings, and catchment hydrology data for river valley slopes.',
  },
  {
    slug: 'gpm-imerg',
    name: 'NASA GPM IMERG Precipitation',
    category: 'rainfall',
    provider: 'NASA Earthdata / JAXA',
    access_type: 'account_or_file_import',
    provenance: 'cached_modelled',
    status: 'configured',
    license_name: 'NASA Open Data',
    credential_env: 'NASA_EARTHDATA_TOKEN',
    last_success_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    freshness_seconds: 10800,
    metadata: { product: 'GPM 3IMERGHHL v06' },
    credential_configured: true,
    file_import_available: true,
    provider_adapter_status: 'available',
    accepted_formats: ['.nc', '.h5', '.tif', '.json'],
    authorization_required: false,
    operator_guidance: 'Global Precipitation Measurement half-hourly multi-satellite precipitation estimates at 0.1° resolution.',
  },
  {
    slug: 'era5-land',
    name: 'ECMWF ERA5-Land Reanalysis',
    category: 'weather_soil',
    provider: 'Copernicus Climate Data Store (ECMWF)',
    access_type: 'account_or_file_import',
    provenance: 'cached_modelled',
    status: 'configured',
    license_name: 'Copernicus License',
    credential_env: 'CDS_API_KEY',
    last_success_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    freshness_seconds: 43200,
    metadata: { resolution_km: 9.0, variable: 'Total precipitation & Volumetric soil water' },
    credential_configured: true,
    file_import_available: true,
    provider_adapter_status: 'available',
    accepted_formats: ['.nc', '.grib'],
    authorization_required: false,
    operator_guidance: 'Historical baseline meteorological and hydrological reanalysis back to 1950.',
  },
  {
    slug: 'smap',
    name: 'NASA SMAP Soil Moisture',
    category: 'soil',
    provider: 'NASA Earthdata / JPL',
    access_type: 'account_or_file_import',
    provenance: 'cached_observed',
    status: 'configured',
    license_name: 'NASA Open Data',
    credential_env: 'NASA_EARTHDATA_TOKEN',
    last_success_at: new Date(Date.now() - 3600000 * 18).toISOString(),
    freshness_seconds: 86400,
    metadata: { sensor: 'L-band Radiometer 9km' },
    credential_configured: true,
    file_import_available: true,
    provider_adapter_status: 'available',
    accepted_formats: ['.h5', '.nc'],
    authorization_required: false,
    operator_guidance: 'Spaceborne radar/radiometer measurements of top 5cm surface soil moisture used to calibrate saturation thresholds.',
  },
  {
    slug: 'nasa-coolr',
    name: 'NASA COOLR Landslide Repository',
    category: 'landslides',
    provider: 'NASA Goddard Space Flight Center',
    access_type: 'public_export',
    provenance: 'static_reference',
    status: 'import_available',
    license_name: 'Open Government Data',
    credential_env: 'No secret required',
    last_success_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    freshness_seconds: 604800,
    metadata: { records_count: 12400 },
    credential_configured: false,
    file_import_available: true,
    provider_adapter_status: 'import_available',
    accepted_formats: ['.csv', '.json', '.geojson'],
    authorization_required: false,
    operator_guidance: 'Global cooperative open online landslide database for validating model susceptibility predictions.',
  },
  {
    slug: 'hydrosheds',
    name: 'HydroSHEDS Catchment & Flow Basin',
    category: 'hydrology',
    provider: 'World Wildlife Fund (WWF) / USGS',
    access_type: 'file_import',
    provenance: 'static_reference',
    status: 'import_available',
    license_name: 'Open Attribution License',
    credential_env: 'No secret required',
    last_success_at: new Date(Date.now() - 3600000 * 72).toISOString(),
    freshness_seconds: 2592000,
    metadata: { resolution_arcsec: 3 },
    credential_configured: false,
    file_import_available: true,
    provider_adapter_status: 'import_available',
    accepted_formats: ['.tif', '.geojson', '.shp.zip'],
    authorization_required: false,
    operator_guidance: 'High-resolution digital drainage directions, flow accumulation, and river network vectors.',
  },
  {
    slug: 'worldpop',
    name: 'WorldPop High-Resolution Population',
    category: 'population',
    provider: 'University of Southampton',
    access_type: 'file_import',
    provenance: 'static_reference',
    status: 'import_available',
    license_name: 'Creative Commons Attribution 4.0',
    credential_env: 'No secret required',
    last_success_at: new Date(Date.now() - 3600000 * 96).toISOString(),
    freshness_seconds: 2592000,
    metadata: { resolution_m: 100 },
    credential_configured: false,
    file_import_available: true,
    provider_adapter_status: 'import_available',
    accepted_formats: ['.tif', '.csv'],
    authorization_required: false,
    operator_guidance: 'Fine-scale 100m population distribution datasets used to calculate human vulnerability and village exposure scores.',
  },
  {
    slug: 'openstreetmap',
    name: 'OpenStreetMap Mountain Highway Network',
    category: 'infrastructure',
    provider: 'OpenStreetMap Foundation',
    access_type: 'public_api',
    provenance: 'static_reference',
    status: 'configured',
    license_name: 'ODbL 1.0',
    attribution: '© OpenStreetMap contributors',
    credential_env: 'No secret required',
    last_success_at: new Date(Date.now() - 1800000).toISOString(),
    freshness_seconds: 3600,
    metadata: { highway_classes: ['motorway', 'trunk', 'primary', 'secondary', 'tertiary'] },
    credential_configured: true,
    file_import_available: false,
    provider_adapter_status: 'available',
    accepted_formats: ['.osm', '.pbf', '.geojson'],
    authorization_required: false,
    operator_guidance: 'Road centerlines, bridges, tunnels, and elevation cuts across National Highways (NH-10, NH-29, NH-106, NH-206).',
  },
];

export const mockIngestionRuns: IngestionRun[] = [
  {
    id: 1084,
    source_slug: 'open-meteo',
    source_name: 'Open-Meteo High-Resolution Forecast',
    status: 'succeeded',
    started_at: new Date(Date.now() - 15 * 60000).toISOString(),
    finished_at: new Date(Date.now() - 14 * 60000).toISOString(),
    records_read: 864,
    records_written: 864,
    quality_flags: ['verified_temporal_continuity', 'no_missing_values'],
    ingestion_method: 'automated_cron_adapter',
    media_type: 'application/json',
    checksum: 'e7b8c9d0f1a23456789abcdef0123456789abcdef0123456789abcdef0123456',
  },
  {
    id: 1083,
    source_slug: 'cdse-process',
    source_name: 'Copernicus Sentinel-1 GRD SAR',
    status: 'succeeded',
    started_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    finished_at: new Date(Date.now() - 3.8 * 3600000).toISOString(),
    records_read: 3420,
    records_written: 3420,
    quality_flags: ['sar_backscatter_calibrated', 'speckle_filtered'],
    ingestion_method: 'satellite_worker_pipeline',
    media_type: 'image/tiff',
    checksum: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
  },
  {
    id: 1082,
    source_slug: 'gsi',
    source_name: 'GSI Bhusanket / NLSM Landslides',
    status: 'succeeded',
    started_at: new Date(Date.now() - 12 * 3600000).toISOString(),
    finished_at: new Date(Date.now() - 11.9 * 3600000).toISOString(),
    records_read: 142,
    records_written: 142,
    quality_flags: ['operator_verified', 'nlsm_polygon_validated'],
    ingestion_method: 'authorized_file_import',
    original_filename: 'gsi_nlsm_meghalaya_sikkim_v2.geojson',
    media_type: 'application/geo+json',
    checksum: '3f4e5d6c7b8a9f0e1d2c3b4a5f6e7d8c9b0a1f2e3d4c5b6a7f8e9d0c1b2a3f4e',
  },
  {
    id: 1081,
    source_slug: 'imd',
    source_name: 'IMD Doppler Radar Scan',
    status: 'succeeded',
    started_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    finished_at: new Date(Date.now() - 1.95 * 3600000).toISOString(),
    records_read: 1280,
    records_written: 1280,
    quality_flags: ['radar_ground_clutter_removed'],
    ingestion_method: 'authorized_file_import',
    original_filename: 'imd_sohra_radar_reflectivity_grid.h5',
    media_type: 'application/x-hdf5',
    checksum: '7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b',
  },
  {
    id: 1080,
    source_slug: 'india-wris',
    source_name: 'CWC / India-WRIS River Gauges',
    status: 'succeeded',
    started_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    finished_at: new Date(Date.now() - 4.95 * 3600000).toISOString(),
    records_read: 94,
    records_written: 94,
    quality_flags: ['cwc_gauge_discharge_synced'],
    ingestion_method: 'authorized_file_import',
    original_filename: 'cwc_brahmaputra_discharge_2026.csv',
    media_type: 'text/csv',
    checksum: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
  },
];
